# Generated by Django 5.0.1 on 2024-04-29 07:11

import app_v1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(default=app_v1.models.generate_unique_po_number, max_length=5, unique=True),
        ),
    ]
